### ISSUE TITLE
Migliorare il controllo sui momenti delle distribuzioni dei rumori colorati

### ISSUE THREAD

**Issue by savaroskij** [chftyrol/lammps-colored-noises#1]
Analizzando i dati prodotti da `tester.x` per alpha diverso da 0 con `cntester`, ottengo dei valori insensati.

test effettuati e risultati:

>``` 
> # savo @ geuleroo in ~/Università/Magistrale/corsi/Dinamica_Molecolare/lammps-colored-noise/testing on git:master x [19:13:36]
>$ for i in {1..100}; do ./tester.x -N 10000 -s $i -a 1 -d 3 | awk '{print $2}' >> test_data1.txt; done
># savo @ geuleroo in ~/Università/Magistrale/corsi/Dinamica_Molecolare/lammps-colored-noise/testing on git:master x [19:30:45]
>$ ./cntester test_data1.txt 10000
>Noise Expectation Value: 0.37302447080550116
>Noise Expectation Value Std. Deviation: 5.067659086601452
>Noise Std. Deviation: 10.445058602335623
>Noise Std. Deviation Std. Deviation: 0.7069280067117708
>```

>```
># savo @ geuleroo in ~/Università/Magistrale/corsi/Dinamica_Molecolare/lammps-colored-noises/testing on git:master x [19:18:11] C:130
>$ for i in {1..100}; do ./tester.x -N 10000 -s $i -a 2 -d 3 | awk '{print $2}' >> test_data2.txt; done
># savo @ geuleroo in ~/Università/Magistrale/corsi/Dinamica_Molecolare/lammps-colored-noises/testing on git:master x [19:22:35] C:130
>$ ./cntester test_data2.txt 10000
>Noise Expectation Value: 25.338134219266575
>Noise Expectation Value Std. Deviation: 369.59033689779886
>Noise Std. Deviation: 228.16096833091748
>Noise Std. Deviation Std. Deviation: 98.96374808398005
>```

Con il rumore bianco non ho problemi invece (anche testando diverse deviazioni standard).
I metodi con cui analizzo i dati non dipendono in alcun modo da alpha: se danno risultato sensati per un tipo di rumore, devono darne per qualsiasi tipo.
@chftyrol , cosa ne pensi?

**Comment by chftyrol** [comment]
Dunque vedo ora. Ho testato anche sulla mia macchina quello che dici e si verifica la stessa cosa. 

Sinceramente non sono sicuro che i valori di rumore siano insensati come dici. In linea di principio non vedo perchè la trasformazione che si fa per colorare il rumore dovrebbe conservare i valori dei momenti delle distribuzioni associate. La matrice di risposta in spazio trasformato è sì diagonale... Ma non è affatto unitaria, il che rende l'intera trasformazione `DFT => Risposta => antiDFT` una mappa che non è unitaria. Magari questa argomentazione non è rilevante, magari sì. Mi documenterò e penserò meglio su questo aspetto.

In ogni caso, quello che salta all'occhio è la varianza molto grossa. In entrambi i casi che menzioni tu, il valore di aspettazione +/- la devstd contiene lo 0. Perciò non mi sembra un risultato così assurdo. Prova a guardare il grafico tipo del rumore browniano al variare della `samplesize`: vedrai che si allontana anche di parecchio dallo 0, ma sui lunghi tempi la situazione tra valori positivi e negativi è piuttosto bilanciata.

Insomma, con una varianza così grossa da un seed all'altro, assegnando noi ad ogni particella una (anzi 3) distribuzioni con seed differenti non mi sembra che il fatto di non avere media nulla su un numero piccolo come 10000 time step possa far sì che il nostro rumore faccia traslare il sistema in toto.

In breve, non sono convinto che questa sia una issue, ma mi documenterò in proposito e verificherò questi pensieri sparsi :)

**Comment by chftyrol** [comment]
Scrivo qui per tenere traccia sulla questione.

Dopo approfondimenti teorici la realizzazione del fatto che la varianza dei rumori colorati cresce monotonamente con il tempo, sotto consiglio del prof, ho implementato (nella branch `leaky`) la possibilita' di applicare un filtro passa basso (integratore leaky). Tagliando le alte frequenze il problema sull'intensita' esplosiva del rumore e' arginato. 

Rimangono alcune questioni da risolvere:

- Quanto impatta questa soluzione sulle autocorrelazioni?
- Come scegliere con ragionevolezza una costante di tempo per il filtro passa basso?
- Come predire la varianza del rumore cosi' generato?
